<?php
think\Route::rule('addBook','index/base/addbook');
think\Route::rule('editBook','index/base/editbook');
think\Route::rule('deleteBook','index/base/deletebook');
think\Route::rule('borrowBook','index/base/borrowbook1');
think\Route::rule("search",'index/base/search2');
think\Route::rule('searchBook','admin/admin/searchbook');
think\Route::rule('login','index/index/login');
think\Route::rule('register','index/index/register');
think\Route::rule('admin','admin/admin/admin');
think\Route::rule('exit','admin/admin/exitBack');
think\Route::rule('home','admin/admin/home');
think\Route::rule('book','admin/admin/book');
think\Route::rule('borrow','admin/admin/borrow');
think\Route::rule('back','admin/admin/back');
think\Route::rule('overtime','admin/admin/overtime');
think\Route::rule('users','admin/admin/users');
think\Route::rule('about','admin/admin/about');
think\Route::rule('system','admin/admin/system');
think\Route::rule('user','user/user/user');
?>